server:
  port: '8888'

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://10.176.34.74:3306/project?&useSSL=false&allowMultiQueries=true&autoReconnect=true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.hello.cigarettes.domain


